name: CI

# Triggers the workflow on push or pull request events but only for the "main" branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.4.1
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Check commit messages
        uses: GsActions/commit-message-checker@v1
        with:
          pattern: "^(?!WIP).*$"
          error: "The first line cannot start with WIP"
          excludeDescription: "true"
          excludeTitle: "true"
          checkAllCommitMessages: "true"
          accessToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & test the denotational semantics Gradle project
        uses: gradle/gradle-build-action@v2.3.0
        with:
          build-root-directory: denotational
          arguments: test

      - name: Build & test the operational implementation Gradle project
        uses: gradle/gradle-build-action@v2.3.0
        with:
          build-root-directory: operational
          arguments: test
